# Generated by Django 4.2.27 on 2025-12-26 09:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ApiKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("key_prefix", models.CharField(editable=False, max_length=8)),
                ("key_hash", models.CharField(db_index=True, editable=False, max_length=64)),
                (
                    "scope",
                    models.CharField(
                        choices=[("full", "Full Access"), ("read", "Read Only")],
                        default="full",
                        max_length=20,
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "api_keys",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(help_text="Brand display name", max_length=255)),
                (
                    "slug",
                    models.SlugField(help_text="URL-safe identifier", max_length=100, unique=True),
                ),
                (
                    "prefix",
                    models.CharField(
                        help_text="License key prefix (e.g., 'RM' for RankMath)",
                        max_length=10,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "brands",
                "ordering": ["name"],
            },
        ),
        migrations.AddIndex(
            model_name="brand",
            index=models.Index(fields=["slug"], name="brands_slug_6a4b1c_idx"),
        ),
        migrations.AddIndex(
            model_name="brand",
            index=models.Index(fields=["prefix"], name="brands_prefix_92a708_idx"),
        ),
        migrations.AddField(
            model_name="apikey",
            name="brand",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="api_keys",
                to="brands.brand",
            ),
        ),
        migrations.AddIndex(
            model_name="apikey",
            index=models.Index(fields=["key_hash"], name="api_keys_key_has_8f2f29_idx"),
        ),
        migrations.AddIndex(
            model_name="apikey",
            index=models.Index(fields=["brand", "scope"], name="api_keys_brand_i_69e9f7_idx"),
        ),
    ]
