# Generated by Django 4.2.27 on 2025-12-26 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("brands", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="brand",
            name="prefix_length_valid",
        ),
    ]
