# Generated by Django 4.2.27 on 2025-12-26 09:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Activation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "instance_identifier",
                    models.CharField(help_text="URL, hostname, or machine ID", max_length=500),
                ),
                (
                    "instance_metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional instance information"
                    ),
                ),
                ("activated_at", models.DateTimeField(auto_now_add=True)),
                ("last_checked_at", models.DateTimeField(auto_now=True)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "db_table": "activations",
                "ordering": ["-activated_at"],
            },
        ),
    ]
