# Generated by Django 4.2.27 on 2025-12-26 09:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("licenses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "instance_identifier",
                    models.CharField(help_text="URL, hostname, or machine ID", max_length=500),
                ),
                (
                    "instance_metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional instance information"
                    ),
                ),
                ("activated_at", models.DateTimeField(auto_now_add=True)),
                ("last_checked_at", models.DateTimeField(auto_now=True)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "license",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activations",
                        to="licenses.license",
                    ),
                ),
            ],
            options={
                "db_table": "activations",
                "ordering": ["-activated_at"],
                "indexes": [
                    models.Index(
                        fields=["license", "instance_identifier"],
                        name="activations_license_953be5_idx",
                    ),
                    models.Index(
                        fields=["license", "is_active"], name="activations_license_5b9a24_idx"
                    ),
                    models.Index(
                        fields=["license", "is_active", "activated_at"],
                        name="activations_license_9649b5_idx",
                    ),
                ],
                "unique_together": {("license", "instance_identifier")},
            },
        ),
    ]
