# Generated by Django 4.2.27 on 2025-12-26 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("activations", "0001_initial"),
        ("licenses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activation",
            name="license",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activations",
                to="licenses.license",
            ),
        ),
        migrations.AddIndex(
            model_name="activation",
            index=models.Index(
                fields=["license", "instance_identifier"], name="activations_license_953be5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activation",
            index=models.Index(
                fields=["license", "is_active"], name="activations_license_5b9a24_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activation",
            index=models.Index(
                fields=["license", "is_active", "activated_at"],
                name="activations_license_9649b5_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="activation",
            unique_together={("license", "instance_identifier")},
        ),
    ]
