# Generated by Django 4.2.27 on 2025-12-26 09:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("brands", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("entity_type", models.CharField(max_length=50)),
                ("entity_id", models.UUIDField()),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("license_key_created", "License Key Created"),
                            ("license_created", "License Created"),
                            ("license_renewed", "License Renewed"),
                            ("license_suspended", "License Suspended"),
                            ("license_resumed", "License Resumed"),
                            ("license_cancelled", "License Cancelled"),
                            ("activation_created", "Activation Created"),
                            ("activation_deleted", "Activation Deleted"),
                        ],
                        max_length=50,
                    ),
                ),
                ("changes", models.JSONField(default=dict, help_text="Details of the change")),
                ("actor", models.CharField(help_text="Who performed the action", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "audit_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IdempotencyKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("key", models.CharField(db_index=True, max_length=255, unique=True)),
                (
                    "response_data",
                    models.JSONField(help_text="Cached response for idempotent replay"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
            ],
            options={
                "db_table": "idempotency_keys",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LicenseKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("key", models.CharField(db_index=True, max_length=100, unique=True)),
                (
                    "key_hash",
                    models.CharField(
                        db_index=True, help_text="Hashed version for secure lookup", max_length=64
                    ),
                ),
                ("customer_email", models.EmailField(db_index=True, max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="license_keys",
                        to="brands.brand",
                    ),
                ),
            ],
            options={
                "db_table": "license_keys",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="License",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("valid", "Valid"),
                            ("suspended", "Suspended"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        default="valid",
                        max_length=20,
                    ),
                ),
                (
                    "seat_limit",
                    models.IntegerField(default=1, help_text="Maximum number of activations"),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "license_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="licenses",
                        to="licenses.licensekey",
                    ),
                ),
            ],
            options={
                "db_table": "licenses",
                "ordering": ["-created_at"],
            },
        ),
    ]
