# Generated by Django 4.2.27 on 2025-12-26 09:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
        ("brands", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LicenseKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("key", models.CharField(db_index=True, max_length=100, unique=True)),
                (
                    "key_hash",
                    models.CharField(
                        db_index=True, help_text="Hashed version for secure lookup", max_length=64
                    ),
                ),
                ("customer_email", models.EmailField(db_index=True, max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="license_keys",
                        to="brands.brand",
                    ),
                ),
            ],
            options={
                "db_table": "license_keys",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="License",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("valid", "Valid"),
                            ("suspended", "Suspended"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        default="valid",
                        max_length=20,
                    ),
                ),
                (
                    "seat_limit",
                    models.IntegerField(default=1, help_text="Maximum number of activations"),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "license_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="licenses",
                        to="licenses.licensekey",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="licenses",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "db_table": "licenses",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IdempotencyKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("key", models.CharField(db_index=True, max_length=255, unique=True)),
                (
                    "response_data",
                    models.JSONField(help_text="Cached response for idempotent replay"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="brands.brand"
                    ),
                ),
            ],
            options={
                "db_table": "idempotency_keys",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("entity_type", models.CharField(max_length=50)),
                ("entity_id", models.UUIDField()),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("license_key_created", "License Key Created"),
                            ("license_created", "License Created"),
                            ("license_renewed", "License Renewed"),
                            ("license_suspended", "License Suspended"),
                            ("license_resumed", "License Resumed"),
                            ("license_cancelled", "License Cancelled"),
                            ("activation_created", "Activation Created"),
                            ("activation_deleted", "Activation Deleted"),
                        ],
                        max_length=50,
                    ),
                ),
                ("changes", models.JSONField(default=dict, help_text="Details of the change")),
                ("actor", models.CharField(help_text="Who performed the action", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="brands.brand",
                    ),
                ),
            ],
            options={
                "db_table": "audit_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="licensekey",
            index=models.Index(fields=["key"], name="license_key_key_8fecb2_idx"),
        ),
        migrations.AddIndex(
            model_name="licensekey",
            index=models.Index(fields=["key_hash"], name="license_key_key_has_aa782e_idx"),
        ),
        migrations.AddIndex(
            model_name="licensekey",
            index=models.Index(
                fields=["customer_email", "brand"], name="license_key_custome_f32e71_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="license",
            index=models.Index(
                fields=["license_key", "product"], name="licenses_license_1d5c38_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="license",
            index=models.Index(
                fields=["license_key", "status"], name="licenses_license_5a9496_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="license",
            index=models.Index(fields=["status"], name="licenses_status_c60f55_idx"),
        ),
        migrations.AddIndex(
            model_name="license",
            index=models.Index(fields=["expires_at"], name="licenses_expires_d6ad63_idx"),
        ),
        migrations.AddIndex(
            model_name="license",
            index=models.Index(
                fields=["license_key", "status", "expires_at"], name="licenses_license_6c0a5e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="license",
            constraint=models.CheckConstraint(
                check=models.Q(("seat_limit__gte", 1)), name="seat_limit_positive"
            ),
        ),
        migrations.AddIndex(
            model_name="idempotencykey",
            index=models.Index(fields=["key"], name="idempotency_key_0fd07b_idx"),
        ),
        migrations.AddIndex(
            model_name="idempotencykey",
            index=models.Index(fields=["brand", "key"], name="idempotency_brand_i_019ac1_idx"),
        ),
        migrations.AddIndex(
            model_name="idempotencykey",
            index=models.Index(fields=["expires_at"], name="idempotency_expires_6c9d28_idx"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["brand", "entity_type", "entity_id"], name="audit_logs_brand_i_375aa1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["created_at"], name="audit_logs_created_262184_idx"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["action"], name="audit_logs_action_31f574_idx"),
        ),
    ]
