# Generated by Django 4.2.27 on 2025-12-26 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
        ("brands", "0001_initial"),
        ("licenses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="license",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="licenses",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="idempotencykey",
            name="brand",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="brands.brand"),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="brand",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audit_logs",
                to="brands.brand",
            ),
        ),
        migrations.AddIndex(
            model_name="licensekey",
            index=models.Index(fields=["key"], name="license_key_key_8fecb2_idx"),
        ),
        migrations.AddIndex(
            model_name="licensekey",
            index=models.Index(fields=["key_hash"], name="license_key_key_has_aa782e_idx"),
        ),
        migrations.AddIndex(
            model_name="licensekey",
            index=models.Index(
                fields=["customer_email", "brand"], name="license_key_custome_f32e71_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="license",
            index=models.Index(
                fields=["license_key", "product"], name="licenses_license_1d5c38_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="license",
            index=models.Index(
                fields=["license_key", "status"], name="licenses_license_5a9496_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="license",
            index=models.Index(fields=["status"], name="licenses_status_c60f55_idx"),
        ),
        migrations.AddIndex(
            model_name="license",
            index=models.Index(fields=["expires_at"], name="licenses_expires_d6ad63_idx"),
        ),
        migrations.AddIndex(
            model_name="license",
            index=models.Index(
                fields=["license_key", "status", "expires_at"], name="licenses_license_6c0a5e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="license",
            constraint=models.CheckConstraint(
                check=models.Q(("seat_limit__gte", 1)), name="seat_limit_positive"
            ),
        ),
        migrations.AddIndex(
            model_name="idempotencykey",
            index=models.Index(fields=["key"], name="idempotency_key_0fd07b_idx"),
        ),
        migrations.AddIndex(
            model_name="idempotencykey",
            index=models.Index(fields=["brand", "key"], name="idempotency_brand_i_019ac1_idx"),
        ),
        migrations.AddIndex(
            model_name="idempotencykey",
            index=models.Index(fields=["expires_at"], name="idempotency_expires_6c9d28_idx"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["brand", "entity_type", "entity_id"], name="audit_logs_brand_i_375aa1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["created_at"], name="audit_logs_created_262184_idx"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["action"], name="audit_logs_action_31f574_idx"),
        ),
    ]
