# Generated by Django 4.2.27 on 2025-12-26 09:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("brands", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(help_text="Product display name", max_length=255)),
                ("slug", models.SlugField(help_text="URL-safe identifier", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="brands.brand",
                    ),
                ),
            ],
            options={
                "db_table": "products",
                "ordering": ["brand", "name"],
                "indexes": [
                    models.Index(fields=["brand", "slug"], name="products_brand_i_109c41_idx")
                ],
                "unique_together": {("brand", "slug")},
            },
        ),
    ]
